# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    remappings:
      - 'ds-test/=lib/ds-test/src/'
      - 'forge-std/=lib/forge-std/src/'
      - 'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
      - 'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
